### ISSUE TITLE
Version 1.3.0 might have broken the keyboard

### ISSUE THREAD

**Issue by LorenzGit** [mesmotronic/air-fullscreen-ane#12] opened 2015-04-28 06:00 UTC
With the new version 1.3.0 when you use the keyboard on an input text the system bar goes up and doesn't go away.

mode: direct, Air 17 and Air 18. Android Lollipop

**Comment by neilrackett** [comment] 2015-04-28 08:24
Good spot. Should be fixed now: can you download the latest ANE from the `build` folder of the repo and confirm the issue is resolved on your device(s)? (if it is, I'll push a new 1.8.1 release)

**Comment by neilrackett** [comment] 2015-04-28 08:57
Looks good here, so I'm going to close this issue, but if you spot anything just re-open it and I'll take a look.

**Closed by neilrackett** 2015-04-28 08:57 UTC
